import type { RawOpportunity } from "./types";

/** Programs CS students often miss — curated with stable metadata; deadlines refreshed on sync where possible. */
export const CURATED_PROGRAMS: RawOpportunity[] = [
  {
    externalId: "gsoc",
    title: "Google Summer of Code (GSoC)",
    description:
      "Paid open-source internship program. Contribute to mentor organizations over the summer, learn real-world software engineering, and build your portfolio.",
    type: "OPEN_SOURCE",
    organization: "Google",
    isRemote: true,
    url: "https://summerofcode.withgoogle.com/",
    applyUrl: "https://summerofcode.withgoogle.com/",
    domains: ["open-source", "software-engineering"],
    tags: ["gsoc", "open-source", "internship", "summer"],
    skillsRequired: ["git", "programming", "communication"],
    eligibility: "University students 18+; check official eligibility each year",
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "outreachy",
    title: "Outreachy",
    description:
      "Paid remote internships in open source for people from groups underrepresented in tech. Three-month mentorship with FOSS communities.",
    type: "FELLOWSHIP",
    organization: "Outreachy",
    isRemote: true,
    url: "https://www.outreachy.org/",
    domains: ["open-source", "diversity"],
    tags: ["outreachy", "open-source", "paid-internship"],
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "lfx-mentorship",
    title: "LFX Mentorship (Linux Foundation)",
    description:
      "Structured mentorship on CNCF and Linux Foundation projects. Stipend-based program connecting mentees with maintainers.",
    type: "MENTORSHIP",
    organization: "Linux Foundation",
    isRemote: true,
    url: "https://mentorship.lfx.linuxfoundation.org/",
    domains: ["open-source", "cloud-native", "linux"],
    tags: ["lfx", "cncf", "mentorship", "linux"],
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "mlh-fellowship",
    title: "MLH Fellowship",
    description:
      "Remote internship alternative: collaborate in small teams on production-grade projects with mentorship from MLH.",
    type: "FELLOWSHIP",
    organization: "Major League Hacking",
    isRemote: true,
    url: "https://fellowship.mlh.io/",
    domains: ["software-engineering", "open-source"],
    tags: ["mlh", "fellowship", "remote"],
    isCurated: true,
  },
  {
    externalId: "icpc",
    title: "ICPC — International Collegiate Programming Contest",
    description:
      "World's premier collegiate algorithmic programming contest. Regional contests lead to World Finals; strong signal for competitive programming careers.",
    type: "COMPETITION",
    organization: "ICPC Foundation",
    url: "https://icpc.global/",
    domains: ["algorithms", "competitive-programming"],
    tags: ["icpc", "competitive-programming", "contest"],
    skillsRequired: ["algorithms", "data-structures", "c++", "java", "python"],
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "ioi",
    title: "International Olympiad in Informatics (IOI)",
    description:
      "Annual olympiad in informatics for secondary school students. National selection contests feed into the international team.",
    type: "COMPETITION",
    organization: "IOI",
    url: "https://ioinformatics.org/",
    domains: ["competitive-programming"],
    tags: ["ioi", "olympiad"],
    isCurated: true,
  },
  {
    externalId: "codeforces",
    title: "Codeforces Rounds & GYM",
    description:
      "Regular competitive programming contests. Rated rounds build your profile for internships and quant roles.",
    type: "COMPETITION",
    organization: "Codeforces",
    url: "https://codeforces.com/",
    domains: ["competitive-programming"],
    tags: ["codeforces", "cp"],
    isCurated: true,
  },
  {
    externalId: "atcoder",
    title: "AtCoder Contests",
    description:
      "Japanese competitive programming platform with ABC/ARC/AGC contests. Popular for interview prep and CP growth.",
    type: "COMPETITION",
    organization: "AtCoder",
    url: "https://atcoder.jp/",
    domains: ["competitive-programming"],
    tags: ["atcoder", "cp"],
    isCurated: true,
  },
  {
    externalId: "hacktoberfest",
    title: "Hacktoberfest",
    description:
      "Annual celebration of open source encouraging meaningful contributions to public repositories.",
    type: "OPEN_SOURCE",
    organization: "DigitalOcean / community",
    isRemote: true,
    url: "https://hacktoberfest.com/",
    domains: ["open-source"],
    tags: ["hacktoberfest", "open-source"],
    isCurated: true,
  },
  {
    externalId: "github-education",
    title: "GitHub Student Developer Pack",
    description:
      "Free tools and credits for students: domains, cloud credits, IDEs, and more — essential for building projects cheaply.",
    type: "SCHOLARSHIP",
    organization: "GitHub",
    url: "https://education.github.com/pack",
    domains: ["tools", "education"],
    tags: ["github", "student-pack"],
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "microsoft-learn-student-ambassadors",
    title: "Microsoft Learn Student Ambassadors",
    description:
      "Leadership program for student technologists: events, swag, Azure credits, and mentorship from Microsoft.",
    type: "FELLOWSHIP",
    organization: "Microsoft",
    url: "https://studentambassadors.microsoft.com/",
    domains: ["community", "cloud"],
    tags: ["microsoft", "student-ambassador"],
    isCurated: true,
  },
  {
    externalId: "google-code-jam",
    title: "Google Code Jam / Kick Start",
    description:
      "Google's global programming competitions. Kick Start offers flexible round timing; Code Jam is the flagship contest.",
    type: "COMPETITION",
    organization: "Google",
    url: "https://codingcompetitions.withgoogle.com/",
    domains: ["competitive-programming"],
    tags: ["google", "code-jam", "kick-start"],
    isCurated: true,
  },
  {
    externalId: "meta-hacker-cup",
    title: "Meta Hacker Cup",
    description:
      "Annual algorithmic programming contest from Meta with global participation and prize pool.",
    type: "COMPETITION",
    organization: "Meta",
    url: "https://www.facebook.com/codingcompetitions/hacker-cup",
    domains: ["competitive-programming"],
    tags: ["meta", "hacker-cup"],
    isCurated: true,
  },
  {
    externalId: "calico",
    title: "Project Calico / Tigera Networking Challenges",
    description:
      "Cloud networking and Kubernetes ecosystem — follow Tigera/Calico community for hackathons, K8s networking learning paths, and CNCF-adjacent opportunities.",
    type: "EVENT",
    organization: "Tigera (Calico)",
    url: "https://www.tigera.io/project-calico/",
    domains: ["kubernetes", "networking", "cloud-native"],
    tags: ["calico", "kubernetes", "cncf"],
    isCurated: true,
  },
  {
    externalId: "season-of-docs",
    title: "Google Season of Docs",
    description:
      "Brings technical writers and open-source projects together for documentation improvements with stipends.",
    type: "OPEN_SOURCE",
    organization: "Google",
    isRemote: true,
    url: "https://developers.google.com/season-of-docs",
    domains: ["documentation", "open-source"],
    tags: ["season-of-docs", "technical-writing"],
    isCurated: true,
  },
  {
    externalId: "season-of-security",
    title: "Google Season of Security",
    description:
      "Contribute security improvements to open-source projects with mentorship and structured timelines.",
    type: "OPEN_SOURCE",
    organization: "Google",
    isRemote: true,
    url: "https://developers.google.com/season-of-security",
    domains: ["security", "open-source"],
    tags: ["security", "open-source"],
    isCurated: true,
  },
  {
    externalId: "replit-bounties",
    title: "Replit Bounties & Hacks",
    description:
      "Paid bounties and hackathons on Replit — practical way to earn while building visible projects.",
    type: "HACKATHON",
    organization: "Replit",
    isRemote: true,
    url: "https://replit.com/bounties",
    domains: ["software-engineering"],
    tags: ["replit", "bounties"],
    isCurated: true,
  },
  {
    externalId: "devpost-hackathons",
    title: "Devpost Hackathons",
    description:
      "Aggregator for online and in-person hackathons from companies and universities. Filter by AI, web, fintech, and more.",
    type: "HACKATHON",
    organization: "Devpost",
    isRemote: true,
    url: "https://devpost.com/hackathons",
    domains: ["hackathons"],
    tags: ["devpost", "hackathon"],
    isCurated: true,
    isFeatured: true,
  },
  {
    externalId: "apache-mentorship",
    title: "Apache Software Foundation — Community & Mentorship",
    description:
      "ASF projects run mentorship programs and Google Summer of Code slots. Gateway to enterprise-grade open source.",
    type: "OPEN_SOURCE",
    organization: "Apache Software Foundation",
    url: "https://www.apache.org/",
    domains: ["open-source", "java", "big-data"],
    tags: ["apache", "open-source"],
    isCurated: true,
  },
  {
    externalId: "cncf-mentoring",
    title: "CNCF Mentoring Programs",
    description:
      "Kubernetes, Prometheus, Envoy, and other CNCF projects participate in LFX and GSoC — critical for cloud-native careers.",
    type: "MENTORSHIP",
    organization: "CNCF",
    url: "https://www.cncf.io/",
    domains: ["cloud-native", "kubernetes"],
    tags: ["cncf", "kubernetes", "cloud"],
    isCurated: true,
  },
];
